<?php

namespace Database\Seeders;

use App\Models\District;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    public function run(): void
    {
        $districts = [
            [
                'name' => 'Kaliwates',
                'slug' => 'kaliwates',
                'latitude' => -8.1795,
                'longitude' => 113.6947,
                'elevation' => 82,
                'river_distance' => 390,
                'population_density' => 4850,
                'drainage_score' => 0.64,
                'waste_reports_count' => 45,
                'flood_reports_count' => 12,
                'ai_predictions_count' => 3,
                'risk_score' => 88,
                'status' => 'critical',
                'action_required' => 'Immediate waste transport required',
            ],
            [
                'name' => 'Sumbersari',
                'slug' => 'sumbersari',
                'latitude' => -8.1668,
                'longitude' => 113.7157,
                'elevation' => 92,
                'river_distance' => 460,
                'population_density' => 5100,
                'drainage_score' => 0.68,
                'waste_reports_count' => 28,
                'flood_reports_count' => 34,
                'ai_predictions_count' => 2,
                'risk_score' => 62,
                'status' => 'monitor',
                'action_required' => 'Drainage inspection required',
            ],
            [
                'name' => 'Patrang',
                'slug' => 'patrang',
                'latitude' => -8.1523,
                'longitude' => 113.7024,
                'elevation' => 84,
                'river_distance' => 350,
                'population_density' => 4200,
                'drainage_score' => 0.72,
                'waste_reports_count' => 52,
                'flood_reports_count' => 41,
                'ai_predictions_count' => 4,
                'risk_score' => 91,
                'status' => 'critical',
                'action_required' => 'Flood monitoring and waste management',
            ],
            [
                'name' => 'Ajung',
                'slug' => 'ajung',
                'latitude' => -8.2117,
                'longitude' => 113.6698,
                'elevation' => 76,
                'river_distance' => 520,
                'population_density' => 3600,
                'drainage_score' => 0.74,
                'waste_reports_count' => 18,
                'flood_reports_count' => 8,
                'ai_predictions_count' => 1,
                'risk_score' => 55,
                'status' => 'monitor',
                'action_required' => 'Deploy sanitation team',
            ],
            [
                'name' => 'Mangli',
                'slug' => 'mangli',
                'latitude' => -8.1611,
                'longitude' => 113.6789,
                'elevation' => 88,
                'river_distance' => 610,
                'population_density' => 3900,
                'drainage_score' => 0.77,
                'waste_reports_count' => 22,
                'flood_reports_count' => 15,
                'ai_predictions_count' => 0,
                'risk_score' => 48,
                'status' => 'safe',
                'action_required' => null,
            ],
            [
                'name' => 'Tegal Besar',
                'slug' => 'tegal-besar',
                'latitude' => -8.1932,
                'longitude' => 113.7231,
                'elevation' => 79,
                'river_distance' => 430,
                'population_density' => 4550,
                'drainage_score' => 0.66,
                'waste_reports_count' => 31,
                'flood_reports_count' => 22,
                'ai_predictions_count' => 2,
                'risk_score' => 65,
                'status' => 'monitor',
                'action_required' => 'Regular maintenance of waste facilities',
            ],
            [
                'name' => 'Arjasa',
                'slug' => 'arjasa',
                'latitude' => -8.0864,
                'longitude' => 113.7422,
                'elevation' => 132,
                'river_distance' => 780,
                'population_density' => 2800,
                'drainage_score' => 0.82,
                'waste_reports_count' => 12,
                'flood_reports_count' => 6,
                'ai_predictions_count' => 0,
                'risk_score' => 35,
                'status' => 'safe',
                'action_required' => null,
            ],
            [
                'name' => 'Ambulu',
                'slug' => 'ambulu',
                'latitude' => -8.3459,
                'longitude' => 113.6079,
                'elevation' => 95,
                'river_distance' => 650,
                'population_density' => 3900,
                'drainage_score' => 0.65,
                'waste_reports_count' => 15,
                'flood_reports_count' => 9,
                'ai_predictions_count' => 1,
                'risk_score' => 42,
                'status' => 'safe',
                'action_required' => null,
            ],
            [
                'name' => 'Balung',
                'slug' => 'balung',
                'latitude' => -8.2814,
                'longitude' => 113.5638,
                'elevation' => 63,
                'river_distance' => 310,
                'population_density' => 3700,
                'drainage_score' => 0.61,
                'waste_reports_count' => 20,
                'flood_reports_count' => 11,
                'ai_predictions_count' => 1,
                'risk_score' => 51,
                'status' => 'monitor',
                'action_required' => 'Preventive maintenance required',
            ],
            [
                'name' => 'Rambipuji',
                'slug' => 'rambipuji',
                'latitude' => -8.2231,
                'longitude' => 113.6142,
                'elevation' => 70,
                'river_distance' => 370,
                'population_density' => 4100,
                'drainage_score' => 0.63,
                'waste_reports_count' => 26,
                'flood_reports_count' => 18,
                'ai_predictions_count' => 2,
                'risk_score' => 58,
                'status' => 'monitor',
                'action_required' => 'Enhanced monitoring needed',
            ],
        ];

        foreach ($districts as $district) {
            District::updateOrCreate(
                ['slug' => $district['slug']],
                $district
            );
        }
    }
}
